spring.application.name=rioPaila
# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/rio_paila
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURACIÓN DEL SERVIDOR (BACKEND)
# ==========================================
server.port=8080
server.servlet.context-path=/api/v1

# ==========================================
# CONFIGURACIÓN SSH (PARA EXPORTACIÓN)
# ==========================================
riopaila.ssh.host=192.168.1.100
riopaila.ssh.port=22
riopaila.ssh.user=admin_ssh
riopaila.ssh.password=secreto_riopaila
riopaila.ssh.remote-path=/home/export/files

# ==========================================
# SEGURIDAD JWT (SECRET KEY)
# ==========================================
# Usa una clave larga y segura para firmar los tokens
security.jwt.secret-key=EstaEsUnaClaveSuperSecretaParaGTCloudRiopaila2026
security.jwt.expiration-time=3600000